spring.application.name=macrotracker

## Database connection

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

## JPA config

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

## Swagger config (true para activar swagger)

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

## Spring Security

application.security.jwt.secret-key=${JWT_SECRET}